#
# SDR System Configuration
# ──────────────────────────────────────────────────────────────

driver: 'airspy'

band: 'vhf'

band_frequencies:
  hf: [7100000, 14200000, 21300000]
  vhf: [144390000, 146520000]
  uhf: [433920000, 446000000]

iq_sample_rate_hz: 2400000

rf_gain_db: 40

scan_duration_sec: 0.5

min_voice_bandwidth_hz: 2000

narrowband_sample_rate_hz: 500000

narrowband_capture_duration_sec: 1.0

#
# FFT
# ──────────────────────────────────────────────────────────────

fft:
  threshold_db: 10.0

  min_distance_hz: 5000

#
# Peak Stability Tracking
# ──────────────────────────────────────────────────────────────

peak_tracker:
  min_hits: 3

  window_sec: 10
